<?php

namespace BlogBundle\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast(){
        return $this->findBy(array(), array('id' => 'DESC'));
    }

}
